"""Fetches nfelo's per-game Elo win probabilities.

nfelo (https://www.nfeloapp.com) is greerreNFL's public NFL Elo rating and
win-probability model. Its pipeline output is committed to the model's own
open-source repository, so the whole table is one CSV over HTTPS with no API
key and no scraping of the site itself -- the same shape of dependency as the
nflverse ``games.csv`` this project already falls back to.

    https://raw.githubusercontent.com/greerreNFL/nfelo/main/output_data/nfelo_games.csv

Only the fetching and caching live here. The arithmetic -- the id format, the
parse, putting an Elo probability on the market's spread scale and blending
the two -- is in ``models/elo.py``, which is pure and never touches the
network. That split is the same one ``models/field_forecast.py`` was extracted
for, and it is what lets the suite exercise every line of the interesting part.

── What it does not cover, which matters more than what it does ────────────

The file is regenerated by nfelo's own pipeline, and it carries **only games
the model has already rated**. Checked against the live file while writing
this: seasons 2009-2026 are present, but the 2026 season had 16 rows -- one
week. A four-week lookahead will therefore find no Elo rating for most of its
horizon, and every one of those games falls back to the market alone.

That is handled rather than worked around: a missing rating is not an error
and is not logged per game, because on any normal Sunday most of the schedule
is missing from it. It does mean the blend is realistically a *this week*
adjustment even when the plan runs seven weeks out, and any measurement of the
blend has to be read with that in mind -- it is not being asked the same
question about week 1 and week 6.
"""
from __future__ import annotations

import csv
import io
import logging
from pathlib import Path
from typing import Dict, Optional

import requests

from data.espn_client import DEFAULT_CACHE_DIR, JSONCache
from models.elo import parse_nfelo_rows

logger = logging.getLogger(__name__)

NFELO_GAMES_CSV_URL = (
    "https://raw.githubusercontent.com/greerreNFL/nfelo/main/output_data/nfelo_games.csv"
)

# The file is regenerated about once a day, so anything under that is asking
# a stranger's server a question it has already answered. Longer than the
# ESPN client's four hours for the same reason.
DEFAULT_CACHE_TTL_HOURS = 12.0

REQUEST_TIMEOUT_SECONDS = 20

# Identifies this tool and points at the upstream project, so an operator
# looking at their logs can tell what is pulling the file and why.
USER_AGENT = (
    "deadpool/0.1 (personal NFL survivor pool tool; "
    "+https://github.com/greerreNFL/nfelo)"
)

CACHE_KEY = "nfelo-games"


def parse_csv(text: str) -> Dict[str, float]:
    """The CSV's text as ``{game_id: home_win_probability}``.

    The file leads with an unnamed index column, which ``csv.DictReader``
    handles by giving it an empty-string key -- harmless, and named here
    because it looks like a parse bug the first time it is seen in a debugger.
    """
    return parse_nfelo_rows(list(csv.DictReader(io.StringIO(text))))


def load_probabilities(
    cache_dir: Optional[Path] = None,
    cache_ttl_hours: float = DEFAULT_CACHE_TTL_HOURS,
    force_refresh: bool = False,
) -> Dict[str, float]:
    """The whole nfelo table as ``{game_id: home_win_probability}``.

    Returns ``{}`` rather than raising when the fetch fails and nothing is
    cached. That is the important behaviour: the Elo blend is an optional
    second opinion layered on a model that works without it, so a third party's
    CSV being unreachable must degrade to market-only probabilities and not
    take the week's picks down with it.

    The parsed table is cached rather than the raw CSV -- it is a twentieth of
    the size and the parse is deterministic, so there is nothing to be gained
    from keeping 1.4 MB of columns this project never reads.
    """
    cache = JSONCache(cache_dir or DEFAULT_CACHE_DIR, cache_ttl_hours)

    if not force_refresh:
        cached = cache.read(CACHE_KEY)
        if isinstance(cached, dict):
            return {str(k): float(v) for k, v in cached.items()}

    try:
        response = requests.get(
            NFELO_GAMES_CSV_URL,
            timeout=REQUEST_TIMEOUT_SECONDS,
            headers={"User-Agent": USER_AGENT, "Accept": "text/csv"},
        )
        response.raise_for_status()
        table = parse_csv(response.text)
    except (requests.RequestException, ValueError) as exc:
        logger.warning("nfelo fetch failed (%s); falling back to cache", exc)
        stale = cache.read(CACHE_KEY, allow_stale=True)
        if isinstance(stale, dict):
            return {str(k): float(v) for k, v in stale.items()}
        logger.warning("no cached nfelo table; win probabilities will be market-only")
        return {}

    if table:
        cache.write(CACHE_KEY, table)
    return table
