/**
 * Capture a real ESPN week as a fixture.
 *
 * The fixtures in fixtures/weeks/ are generated by make-fixtures.mjs, because
 * this repository was built somewhere that cannot reach site.api.espn.com.
 * Generated fixtures are fully sufficient for what they exist for — proving
 * the JavaScript and Python engines reach the same answer from identical input
 * — and blind to exactly one thing: ESPN renaming a field, since they are
 * written from the same understanding of the response that the parser has.
 *
 * This closes that gap. Run it from a machine with network access and it
 * writes a bundle in the same shape, from the real thing.
 *
 *   node scripts/capture-week.mjs --week 3 --season 2025
 *   node scripts/capture-week.mjs --week 3 --season 2025 --name real-w03
 *
 * Then add a run to fixtures/parity-spec.json naming it, regenerate the golden
 * output with `npm run golden`, and the parity suite covers it.
 *
 * An authoring tool, not a build step, for the same reason fetch-fonts is one:
 * it touches the network, `dependencies` is empty, and the suite may never
 * fetch — a test that reaches ESPN passes on a laptop with no internet and
 * then fails on CI.
 */
import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'fixtures/weeks');

const SITE_API = 'https://site.api.espn.com/apis/site/v2/sports/football/nfl';
const CORE_API = 'https://sports.core.api.espn.com/v2/sports/football/leagues/nfl';
const UA = 'deadpool/0.1 (fixture capture; run by hand, rarely)';

// Deliberately slow. This is the Python client's manners, kept for a tool that
// is run by a person a handful of times rather than by an app on a schedule.
const DELAY_MS = 400;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

const arg = (name, fallback = null) => {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
};

async function get(url) {
  await sleep(DELAY_MS);
  const res = await fetch(url, { headers: { 'User-Agent': UA, Accept: 'application/json' } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.json();
}

async function main() {
  const week = Number(arg('week'));
  const season = arg('season');
  const seasonType = Number(arg('seasontype', '2'));
  if (!Number.isInteger(week) || week < 1 || week > 22) {
    console.error('capture-week: --week is required, 1 to 22');
    process.exit(1);
  }

  const query = new URLSearchParams({ week: String(week), seasontype: String(seasonType) });
  if (season) query.set('dates', season);

  console.log(`  scoreboard week ${week}${season ? ` of ${season}` : ''}…`);
  const scoreboard = await get(`${SITE_API}/scoreboard?${query}`);

  const events = scoreboard.events ?? [];
  console.log(`  ${events.length} games`);

  const probabilities = {};
  const odds = {};
  for (const event of events) {
    const competition = (event.competitions ?? [])[0];
    const competitionId = competition?.id ?? event.id;
    if (!event.id || !competitionId) continue;

    // Failures are recorded as an absence rather than aborting the capture. A
    // week where ESPN has not modelled three games is a real week, and one of
    // the more useful fixtures to have.
    try {
      probabilities[event.id] = await get(`${CORE_API}/events/${event.id}/competitions/${competitionId}/probabilities?limit=1`);
    } catch { console.log(`    no probability for ${event.shortName ?? event.id}`); }
    try {
      odds[event.id] = await get(`${CORE_API}/events/${event.id}/competitions/${competitionId}/odds`);
    } catch { console.log(`    no odds for ${event.shortName ?? event.id}`); }
  }

  const name = arg('name', `real-${scoreboard.season?.year ?? season ?? 'x'}-w${String(week).padStart(2, '0')}`);
  mkdirSync(OUT, { recursive: true });
  writeFileSync(join(OUT, `${name}.json`), `${JSON.stringify({
    meta: {
      name,
      capturedBy: 'scripts/capture-week.mjs',
      // A real capture is a snapshot of a moment: the odds moved before it and
      // will move after it, and the game states are whatever they were. Say
      // when, or the fixture is undatable evidence.
      capturedAt: new Date().toISOString(),
      season: scoreboard.season?.year ?? Number(season),
      seasonType,
      week: scoreboard.week?.number ?? week,
      note: 'A real ESPN capture. Unlike the generated fixtures, this can catch a renamed field.',
    },
    scoreboard,
    probabilities,
    odds,
  }, null, 2)}\n`);

  console.log(`\n  → fixtures/weeks/${name}.json`);
  console.log('  Add a run naming it to fixtures/parity-spec.json, then: npm run golden');
}

main().catch((err) => { console.error(`capture-week: ${err.message}`); process.exit(1); });
